
export const TableData = [
  {
    Account_Name: "Beauregard",
    Email: "bship@washington.com",
    Phone_No: "992-466-4898",
    Website: "https://vercel.com",
    Industry: "IT",
    Account_Status: "true",
    Remark: "good",
    Actions: "...",
  },
  {
    Account_Name: "Tanitansy",
    Email: "tpendall2@tripod.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Jackelyn",
    Email: "jcorona3@addtoany.com",
    Phone_No: "992-466-4898",
    Website: "https://vercel.com",
    Industry: "IT",
    Account_Status: "true",
    Remark: "good",
    Actions: "...",
  },
  {
    Account_Name: "Eimile",
    Email: "epridham4@bloomberg.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Walt",
    Email: "wleabeater5@stumbleupon.com",
    Phone_No: "992-466-4898",
    Website: "https://vercel.com",
    Industry: "IT",
    Account_Status: "true",
    Remark: "good",
    Actions: "...",
  },
  {
    Account_Name: "Shelia",
    Email: "sgraybeal6@apache.org",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Meggi",
    Email: "mcoggon7@ucoz.ru",
    Phone_No: "992-466-4898",
    Website: "https://vercel.com",
    Industry: "IT",
    Account_Status: "true",
    Remark: "good",
    Actions: "...",
  },
  {
    Account_Name: "Junette",
    Email: "jbrett8@google.ru",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Goldy",
    Email: "gcella9@prweb.com",
    Phone_No: "992-466-4898",
    Website: "https://vercel.com",
    Industry: "IT",
    Account_Status: "true",
    Remark: "good",
    Actions: "...",
  },
  {
    Account_Name: "Dorrie",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Javier",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Greer",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Brad",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Conni",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Janenna",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Yule",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Clive",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Windham",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Cory",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Claudina",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Saraann",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Meghann",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Lonnard",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Binny",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Antonio",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Buddy",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Liliane",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Brietta",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Crysta",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Bondie",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Sargent",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Simone",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Kaia",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Nikolaus",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Karl",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Taddeo",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Kaila",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Karlee",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Elwood",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Arne",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Desmond",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Micheal",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Brianne",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Cristian",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Stavro",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
  {
    Account_Name: "Donal",
    Email: "dmarkeya@cloudflare.com",
    Phone_No: "992-466-4898",
    Website: "https://google.com",
    Industry: "IT",
    Account_Status: "false",
    Remark: "Nice",
    Actions: "...",
  },
];
